#!/usr/bin/env bash
alias esc="$HOME/.config/sway/config"
alias vim="nvim"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias work="cd ~/Documents/0_git"

alias python="python3"
alias cbp="cat $DOTFILES/zsh/.config/.zsh_profile"
alias ebp="$VIM ~/.zsh_profile"
alias etc="$VIM $DOTFILES/awesome-streamerrc/ThePrimeagen/.tmux.conf"
alias bp="dotFileInstall && source ~/.zshrc"
alias eirc="nvim $XDG_CONFIG_HOME/i3/i3config"
alias dotFileInstall="$DOTFILES/install"

# watch GPU usage refreshing every second
alias wgpu="watch -n 1 nvidia-smi"
