#!/usr/bin/env bash
addToPathFront $DENO_INSTALL
addToPath /usr/local/go/bin
addToPath $GOPATH/bin
addToPath $HOME/work/wrapper
addToPath /usr/local/netflix/tvui-automation-analyzer
addToPath $HOME/.yarn/bin
addToPath /usr/lib/llvm-8/bin
addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup
addToPathFront $HOME/Projects/xota_wasm/xota-rs/tools/wasm-split-24.12.1/bin/wasm-split-debug

# ccache
addToPathFront /usr/lib/ccache
